openapi: 3.0.3
info:
  title: PaymentAPI
  description: Payment API for demonstration purposes.
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
tags:
  - name: payments
    description: Payment operations
paths:
  /api/payments:
    get:
      summary: Get all payments
      operationId: getPayments
      tags:
        - payments
      responses:
        '200':
          description: A list of payments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/payment'
    post:
      summary: Create a new payment
      operationId: createPayment
      tags:
        - payments
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/payment'
      responses:
        '201':
          description: payment created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/payment'
  /api/payments/{paymentId}:
    get:
      summary: Get an payment by ID
      operationId: getPaymentById
      tags:
        - payments
      parameters:
        - name: paymentId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: payment details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/payment'
        '404':
          description: payment not found
components:
  schemas:
    payment:
      type: object
      properties:
        id:
          type: string
        item:
          type: string
        quantity:
          type: integer
        price:
          type: number
          format: float
